import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { HeadContent, Link, Outlet, Scripts, createRootRouteWithContext, useRouter } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { SiteLayout } from "@/components/school/Layout";
function NotFoundComponent(){return <div className="site-container py-24 text-center"><p className="text-xs font-bold uppercase text-accent-foreground">404</p><h1 className="heading-lg mt-4">This page isn't on the school map.</h1><p className="mx-auto mt-5 max-w-md text-muted-foreground">The page may have moved or the address may be incorrect.</p><Link to="/" className="mt-8 inline-flex min-h-11 items-center bg-primary px-6 font-semibold text-primary-foreground">Back to Home</Link></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){const router=useRouter();useEffect(()=>reportLovableError(error,{boundary:"root"}),[error]);return <div className="site-container py-24 text-center"><h1 className="heading-lg">This page didn't load.</h1><p className="mt-4 text-muted-foreground">Please try again or return home.</p><button className="mt-7 min-h-11 bg-primary px-6 font-semibold text-primary-foreground" onClick={()=>{router.invalidate();reset()}}>Try again</button></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{property:"og:type",content:"website"},{property:"og:site_name",content:"DM Public School"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap"},{rel:"icon",href:"/favicon.png",type:"image/png"},{rel:"manifest",href:"/site.webmanifest"}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":["WebSite","School"],name:"DM Public School",address:{"@type":"PostalAddress",addressLocality:"Bengaluru",addressRegion:"Karnataka",addressCountry:"IN"}})}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><SiteLayout><Outlet/></SiteLayout></QueryClientProvider>}
