import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpen, HeartHandshake, ShieldCheck, Trophy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { academicStages, eventItems, newsItems, school } from "@/data/school";
import { AdmissionBand, Eyebrow, PhotoPlaceholder, SectionHeading } from "@/components/school/Blocks";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"DM Public School | Laggere, Bengaluru"},{name:"description",content:"Explore DM Public School in Laggere, Bengaluru—academics, student life, campus information and admissions enquiries."},{property:"og:title",content:"DM Public School | Laggere, Bengaluru"},{property:"og:description",content:"A place to learn, grow and become."},{property:"og:type",content:"website"},{property:"og:url",content:"/"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/"}]}),component:Home});
function Home(){const reasons=[{icon:BookOpen,title:"Strong academic foundations",text:"A structured approach to learning that builds understanding, curiosity and confidence."},{icon:HeartHandshake,title:"Whole-child development",text:"Space for character, communication, creativity and participation alongside academics."},{icon:ShieldCheck,title:"A caring environment",text:"A disciplined and welcoming culture where children can feel known and supported."},{icon:Trophy,title:"Opportunity to participate",text:"Activities that encourage teamwork, expression and healthy challenge."}];return <>
<section className="border-b border-border"><div className="site-container grid min-h-[calc(100dvh-9rem)] gap-9 py-10 lg:grid-cols-[.82fr_1.18fr] lg:items-center lg:py-14"><div className="max-w-xl"><Eyebrow>DM Public School · Bengaluru</Eyebrow><h1 className="heading-xl">{school.tagline}</h1><p className="mt-6 max-w-lg text-lg leading-8 text-muted-foreground">A school community where academic foundations, good values and meaningful experiences help every child move forward with confidence.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/admissions">Admissions <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline"><Link to="/about">Explore the School</Link></Button></div></div><PhotoPlaceholder label="School campus or students in learning"/></div></section>
<section className="site-container grid gap-10 py-16 md:grid-cols-[.72fr_1.28fr] md:py-24"><SectionHeading eyebrow="Our school" title="Learning that shapes capable, considerate young people."/><div><p className="text-lg leading-8">DM Public School brings learning, values and student development together in a focused school environment.</p><p className="mt-5 leading-7 text-muted-foreground">Detailed information about the school philosophy, curriculum and leadership will be added here after verification by the school.</p><Link to="/about" className="mt-7 inline-flex min-h-11 items-center gap-2 font-bold text-primary">About DM Public School <ArrowRight className="size-4"/></Link></div></section>
<section className="border-y border-border bg-secondary"><div className="site-container py-16 md:py-24"><SectionHeading eyebrow="Why DMPS" title="A balanced school experience." copy="Clear priorities for learning and growth, presented without inflated claims."/><div className="mt-12 grid border-t border-border md:grid-cols-2">{reasons.map(({icon:Icon,title,text},i)=><article key={title} className={`border-b border-border py-8 md:px-8 ${i%2===0?"md:border-r md:pl-0":""}`}><Icon className="size-6 text-accent-foreground"/><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-3 max-w-md leading-7 text-muted-foreground">{text}</p></article>)}</div></div></section>
<section className="site-container py-16 md:py-24"><div className="grid gap-8 md:grid-cols-[.65fr_1.35fr]"><SectionHeading eyebrow="Academics" title="A clear path through every stage."/><div className="border-t border-border">{academicStages.map((stage,i)=><div key={stage.title} className="grid gap-3 border-b border-border py-7 sm:grid-cols-[3rem_1fr_1.2fr]"><span className="font-display text-sm font-bold text-accent-foreground">0{i+1}</span><div><h3 className="font-display text-lg font-bold">{stage.title}</h3><p className="mt-1 text-xs text-muted-foreground">{stage.range}</p></div><p className="leading-6 text-muted-foreground">{stage.text}</p></div>)}<Button asChild variant="link" className="mt-6 px-0"><Link to="/academics">Explore Academics <ArrowRight/></Link></Button></div></div></section>
<section className="border-y border-border"><div className="site-container grid lg:grid-cols-2"><PhotoPlaceholder label="Student activities, sports and celebrations"/><div className="flex flex-col justify-center py-12 lg:px-14"><SectionHeading eyebrow="Student life" title="Learning continues beyond the classroom." copy="Activities, sports, clubs and celebrations give students opportunities to participate, collaborate and discover their interests."/><Button asChild variant="link" className="mt-6 w-fit px-0"><Link to="/student-life">Discover Student Life <ArrowRight/></Link></Button></div></div></section>
<section className="site-container py-16 md:py-24"><SectionHeading eyebrow="Admissions" title="A straightforward path to joining DMPS."/><ol className="mt-10 grid border-y border-border md:grid-cols-4">{["Make an enquiry","Speak with the school","Complete the confirmed process","Receive admission guidance"].map((x,i)=><li className="border-b border-border p-6 last:border-0 md:border-b-0 md:border-r md:last:border-r-0" key={x}><span className="text-sm font-bold text-accent-foreground">0{i+1}</span><p className="mt-4 font-display font-bold">{x}</p></li>)}</ol><p className="mt-5 text-sm text-muted-foreground">The exact assessment, documentation and confirmation process is pending verification.</p></section>
<section className="bg-secondary"><div className="site-container py-16 md:py-24"><SectionHeading eyebrow="Updates" title="News & events"/><div className="mt-10 grid gap-px bg-border md:grid-cols-2"><article className="bg-background p-7"><p className="text-xs font-bold uppercase text-accent-foreground">{newsItems[0].category} · Draft</p><h3 className="mt-4 font-display text-2xl font-bold">{newsItems[0].title}</h3><p className="mt-3 text-muted-foreground">{newsItems[0].summary}</p><Link to="/news" className="mt-6 inline-flex font-bold">View news</Link></article><article className="bg-background p-7"><p className="text-xs font-bold uppercase text-accent-foreground">{eventItems[0].category} · Draft</p><h3 className="mt-4 font-display text-2xl font-bold">{eventItems[0].title}</h3><p className="mt-3 text-muted-foreground">{eventItems[0].summary}</p><Link to="/events" className="mt-6 inline-flex font-bold">View events</Link></article></div></div></section><AdmissionBand/></>}
