import { useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
const schema=z.object({parent:z.string().trim().min(2,"Enter the parent or guardian name").max(100),student:z.string().trim().min(2,"Enter the student's name").max(100),grade:z.string().trim().min(1,"Enter the grade or class").max(30),phone:z.string().trim().regex(/^[+0-9 ()-]{7,20}$/,"Enter a valid phone number"),email:z.string().trim().email("Enter a valid email").max(255),message:z.string().trim().max(1000).optional(),website:z.string().max(0)});
type Errors=Partial<Record<keyof z.infer<typeof schema>,string>>;
export function EnquiryForm({kind="admission"}:{kind?:"admission"|"contact"}){const [errors,setErrors]=useState<Errors>({});const [status,setStatus]=useState("");function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const result=schema.safeParse(Object.fromEntries(form));if(!result.success){const next:Errors={};result.error.issues.forEach(i=>{const key=i.path[0] as keyof Errors;if(key&&!next[key])next[key]=i.message});setErrors(next);setStatus("Please correct the highlighted fields.");return}setErrors({});setStatus("Enquiry service is not yet connected. Please contact the school using the verified phone or email once published.");}
const field=(name:keyof Errors,label:string,type="text")=><div><Label htmlFor={`${kind}-${name}`}>{label}</Label><Input id={`${kind}-${name}`} name={name} type={type} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name]?`${kind}-${name}-error`:undefined} className="mt-2 min-h-11"/>{errors[name]&&<p id={`${kind}-${name}-error`} className="mt-1 text-sm text-destructive">{errors[name]}</p>}</div>;
return <form onSubmit={submit} noValidate className="grid gap-5" aria-label={`${kind} enquiry form`}><div className="hidden" aria-hidden="true"><Label htmlFor={`${kind}-website`}>Website</Label><Input id={`${kind}-website`} name="website" tabIndex={-1} autoComplete="off"/></div><div className="grid gap-5 sm:grid-cols-2">{field("parent","Parent/Guardian Name")}{field("student","Student Name")}{field("grade","Grade/Class")}{field("phone","Phone","tel")}{field("email","Email","email")}</div><div><Label htmlFor={`${kind}-message`}>Message <span className="text-muted-foreground">(optional)</span></Label><Textarea id={`${kind}-message`} name="message" className="mt-2 min-h-32" maxLength={1000}/></div>{status&&<p className="border-l-4 border-accent bg-secondary p-4 text-sm" role="status" aria-live="polite">{status}</p>}<Button type="submit" size="lg" className="w-full sm:w-fit">Send Enquiry</Button><p className="text-xs leading-5 text-muted-foreground">By submitting, you agree that the school may contact you about this enquiry. Submission remains disabled until the school connects its secure form service.</p></form>}
