import { Link } from "@tanstack/react-router";
import { Mail, MapPin, Menu, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetClose, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import logo from "@/assets/dmps-logo.png.asset.json";
import { navigation, school } from "@/data/school";

export function SiteHeader() {
  return <header className="border-b border-border bg-background">
    <a href="#main-content" className="sr-only z-[100] bg-primary px-4 py-3 text-primary-foreground focus:not-sr-only focus:fixed focus:left-3 focus:top-3">Skip to content</a>
    <div className="border-b border-border bg-secondary"><div className="site-container flex min-h-9 items-center justify-between gap-4 text-xs text-secondary-foreground"><span className="hidden sm:inline">{school.locality}, {school.city}</span><span className="font-semibold">Admissions information available</span></div></div>
    <div className="site-container grid min-h-20 grid-cols-[minmax(0,1fr)_auto] items-center gap-4 lg:min-h-24">
      <Link to="/" className="flex min-w-0 items-center gap-3" aria-label="DM Public School home"><img src={logo.url} width="64" height="64" className="size-14 shrink-0 object-contain lg:size-16" alt="DM Public School emblem"/><div className="min-w-0"><span className="block truncate font-display text-lg font-extrabold text-primary sm:text-xl">DM Public School</span><span className="hidden text-xs text-muted-foreground sm:block">Learning with purpose. Growing with values.</span></div></Link>
      <nav aria-label="Primary navigation" className="hidden items-center gap-1 lg:flex">{navigation.map((item) => <Link key={item.to} to={item.to} className="px-2 py-3 text-sm font-semibold text-foreground transition-colors hover:text-accent-foreground" activeProps={{className:"text-accent-foreground underline decoration-2 underline-offset-8"}}>{item.label}</Link>)}<Button asChild size="lg" className="ml-2"><Link to="/admissions" data-analytics="admission-cta">Enquire</Link></Button></nav>
      <Sheet><SheetTrigger asChild><Button variant="outline" size="icon" className="min-h-11 min-w-11 lg:hidden" aria-label="Open navigation"><Menu /></Button></SheetTrigger><SheetContent className="w-[88%] max-w-sm"><SheetHeader className="border-b border-border pb-5 text-left"><SheetTitle>DM Public School</SheetTitle><SheetDescription>School navigation</SheetDescription></SheetHeader><nav aria-label="Mobile navigation" className="mt-6 flex flex-col">{navigation.map((item)=><SheetClose asChild key={item.to}><Link to={item.to} className="flex min-h-12 items-center border-b border-border text-base font-semibold">{item.label}</Link></SheetClose>)}<SheetClose asChild><Button asChild size="lg" className="mt-7"><Link to="/admissions">Admissions Enquiry</Link></Button></SheetClose></nav></SheetContent></Sheet>
    </div>
  </header>
}

export function SiteFooter() { return <footer className="border-t border-border bg-primary text-primary-foreground"><div className="site-container grid gap-10 py-12 md:grid-cols-[1.35fr_1fr_1fr] md:py-16"><div><img src={logo.url} width="72" height="72" loading="lazy" className="mb-4 size-16 object-contain" alt="DM Public School emblem"/><h2 className="font-display text-xl font-bold">DM Public School</h2><p className="mt-3 max-w-sm text-sm leading-6 text-primary-foreground/80">A welcoming school community focused on learning, character and the development of every child.</p></div><div><h2 className="footer-heading">Explore</h2><ul className="mt-4 grid grid-cols-2 gap-x-3 gap-y-3 text-sm">{navigation.slice(1).map(i=><li key={i.to}><Link to={i.to} className="text-primary-foreground/80 hover:text-primary-foreground">{i.label}</Link></li>)}</ul></div><div><h2 className="footer-heading">Contact</h2><address className="mt-4 space-y-3 text-sm not-italic text-primary-foreground/80"><p className="flex gap-2"><MapPin className="mt-0.5 size-4 shrink-0"/>{school.address}<br/>{school.locality}, {school.city}</p><p className="flex gap-2"><Phone className="size-4 shrink-0"/>{school.phone}</p><p className="flex gap-2"><Mail className="size-4 shrink-0"/>{school.email}</p></address></div></div><div className="border-t border-primary-foreground/20"><div className="site-container flex flex-col gap-3 py-5 text-xs text-primary-foreground/70 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 DM Public School. All rights reserved.</p><div className="flex gap-5"><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></div></div></div></footer> }

export function SiteLayout({children}:{children:React.ReactNode}) { return <><SiteHeader/><main id="main-content">{children}</main><SiteFooter/></> }
